### ISSUE TITLE
Programm without libUSB?

### ISSUE THREAD

**Issue by DodoProgramms** [pyusb/pyusb#116]
Hey,

I have an important question.
Does my programm run without libUSB installed on the computer, or MUST it be installed.
Because I want to code an USB-Locker for any OS, and I don't want, that everyone has to install LibUSB to run my application.

Dechasa

PS: If LibUSB must be installed, is there any other lib I can use which don't use LibUSB?

**Comment by walac** [comment]
You can define your own backend without libusb.

**Comment by mcuee** [comment]
Closing old issues.
