### ISSUE TITLE
Implement Device.__eq__()

### ISSUE THREAD

**Issue by martijnthe** [pyusb/pyusb#147]
I'd like to be able to write something like:

```
devs = set()
devs |= set(usb.core.find(find_all=True, custom_match=matcher_one))
devs |= set(usb.core.find(find_all=True, custom_match=matcher_two))
```

If `matcher_one` and `matcher_two` both match device XYZ, `devs` will contain two instances of `Device` referring to XYZ. I'd expect `devs` to contain only one instance referring to XYZ.

**Comment by jonasmalacofilho** [comment]
Thoughts on implementing `__eq__` as follows?

```py
def __eq__(self, other):
    return (self.backend, self.bus, self.address) == \
           (other.backend, other.bus, other.address)
```

Essentially defining equality based on the OS's view of the USB tree, but also taking into account the different possible backends.

Cc: @mcuee

**Comment by mcuee** [comment]
Looks good to me.
