### ISSUE TITLE
"IndexError: array index out of range" when reading product property

### ISSUE THREAD

**Issue by c1728p9** [pyusb/pyusb#164]
When reading the product property of a device I occasionally get an array index out or range error. This is on Ubuntu 16.04 when using libusb1. More specifically, I'm seeing this when running usb.core.find using a custom_match which reads the product property.

Exception:
```
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 841, in product
    self._product = util.get_string(self, self.iProduct)
  File "/usr/local/lib/python2.7/dist-packages/usb/util.py", line 330, in get_string
    return buf[2:buf[0]].tostring().decode('utf-16-le')
IndexError: array index out of range
```

**Comment by c1728p9** [comment]
I took a look at the USB traffic when this occurs. A zero length IN transaction is sent in response to the GetDescriptor request during the data stage. If there is a check that "len(buf) > 0" then the IndexError could be prevented.

**Comment by walac** [comment]
Hrm, a more elegant message error is indeed desirable, thanks for the report.
