### ISSUE TITLE
device.read() does not set endpoint read flag

### ISSUE THREAD

**Issue by RenaKunisaki** [pyusb/pyusb#170]
To read from a device, you must manually set the read flag (the highest bit of the endpoint number):

```python
self.dev = usb.core.find(idVendor=self.vid, idProduct=self.pid)
if self.dev.is_kernel_driver_active(interface) is True:
    self.dev.detach_kernel_driver(interface)
    usb.util.claim_interface(self.dev, interface)

data = self.dev.read(self.Endpoint.HID | 0x80,
            length, timeout=100)
```

Otherwise, the program issues a write (OUT) request instead of a read (IN), and I spend an entire day trying to track down the problem.

**Comment by mcuee** [comment]
Not an issue. IN and OUT endpoint are different endpoint. This is the same in libusb-1.0.
