### ISSUE TITLE
About the use of pyusb in the multiprocess

### ISSUE THREAD

**Issue by wbb12** [pyusb/pyusb#174]
I have to communicate with several identical devices by usb. I have communicated with one single device by pyusb with python3.5 successsfully.  however, when it comes to several devices, I  prepared to use multiprocesses to communicate with each devices respectively.  It seems the process will  block the others, and the data received from the device go wrong sometimes. 
is that a fact that the python programes with pyusb can only communicate with on single device at a particular time?

**Comment by rec** [comment]
While I am not the writer of this program, I don't see how you expect this to work. 

There's only one wire.  How do you expect to send more than one message in parallel?

**Comment by walac** [comment]
If they are identical, how do you distinguish them?

**Comment by hardkrash** [comment]
Not that I know how wbb12 does this but I use bus and port numbers.

**Comment by ldnelso2** [comment]
@hardkrash how do you use the bus and port numbers?  This is mentioned in the tutorial, but I can't figure out how to address them to write serial commands to multiple identical devices.

**Comment by mcuee** [comment]
Please use pyusb mailing list for technical support.
