### ISSUE TITLE
ValueError: NULL pointer access

### ISSUE THREAD

**Issue by erezposner** [pyusb/pyusb#178]
I have two barcode readers.  In order to use them both under windows i need to use Zadig and change the default usb driver.
for one i need to use libusb-32 in order for it to work with pyusb.
for the second i need to use libusbK for it to work with pyusb.

i want to use the second one (libusbK) with raspberry pi. but now i always get null pointer error.
the first one works like charm.
i understand i am having driver issue. what must i do ?
thank you
my initialization is shown below if anyone is interested.
thank you

    def InitUSB(self):
        # bc = USB_Device()
        HID_Interface_Class=3
        # Find DevicesList Filtered by idVendor and HIDInterfaceClass
        # devices = usb.core.find(find_all=True)
        devices = usb.core.find(find_all=True, custom_match=find_Device_InterfaceClass(HID_Interface_Class))

        # devices = usb.core.find(find_all=True, idVendor=0x13ba, custom_match=find_Device_InterfaceClass(HID_Interface_Class))#TODO Uncomment if having trouble

        if devices is None:
            raise ValueError('Our device is not connected')
        NumberOfDevicesFound = len(devices.gi_code.co_consts) - 1
        if NumberOfDevicesFound > 1:
            raise ValueError('More Than One Device is connected')

        dev = devices.next()

**Comment by walac** [comment]
`find` function will call `libusb` initialization  functions, which probably is messing things up.

**Comment by erezposner** [comment]
so what are suggesting i should do?

**Comment by walac** [comment]
Do only one call `find` function to return both devices references.

**Comment by erezposner** [comment]
I am only doing one find call. see other rows are commented.

**Comment by walac** [comment]
So, where are you actually caling the second device?

**Comment by erezposner** [comment]
Ok , i guess i wasnt clear. 

i only want to use the second barcode reader (libusbK). during development i used the first one. then i replaced the barcode reader due to its physical dimensions. I was under the assumption  that there won't be any difference between the two.

so what i am saying that i want the code that works with the first one to work with the second. but until now without luck

**Comment by walac** [comment]
Hrm, you can use `PYUSB_DEBUG` and `LIBUSB_DEBUG` environment variables to spot exactly what's going on. It feels like a libusb issue.

**Comment by erezposner** [comment]
I've been playing with it and now i can successfully see the connect to the second barcode.
Finally i understand the difference in behavior between the two barcode readers.

now i have a new problem, the second barcode is seem to operate both as an HID device and also handled by the pyUSB. doing a little digging i saw that the second one has two interface while the first has only one.
with the current code, as i scan a barcode with the second reader the first interface is being listened by the pyusb and the other interface is being handled by the kernel as an hid device.
(while using the first barcode reader the one interface is being listened by the pyusb and everything is working as expected)

so my question is, how can i disable the second interface? is there a way to listen to both interfaces? 
thank you

**Comment by walac** [comment]
Can't you just ignore the hid interface?

**Comment by erezposner** [comment]
i am not what you mean by ignoring. i have no control over it.
Basically, my app displays the user an HTML on chromium (I use Flask && chromium) , and in the background i have a thread that listens to the input from the barcode reader.
now the problem is that every time i scan a barcode it is as if i opened another tab in the chromium.
this is due to the second interface defined as HID.

i also get the value using the first interface && pyUSB.

**Comment by walac** [comment]
by "ignore it" I mean just don't send any commands to it. I am afraid I didn't actually understand your issue.

**Comment by erezposner** [comment]
Ok, i will explain.
i have barcode reader that has two interfaces:
![image](https://cloud.githubusercontent.com/assets/8953700/24680001/e9161222-1997-11e7-9252-0f6909f339cf.png)

Now, as far as the actual program it is as follows: the user sees on chrom an HTML like this:
![image](https://cloud.githubusercontent.com/assets/8953700/24680050/12c82f60-1998-11e7-8ab5-5a9f52bfc453.png)
what i want to do is to listen to any scan and handle it.

When i use barcode reader with only one interface everything works fine (using the code above) , i get the barcode data.

If i use barcode reader with two interfaces what happens is that i get the data from interface 0, and it seems that interface 1 is still bind to the kernel and acts as HID device resulting with this:
![image](https://cloud.githubusercontent.com/assets/8953700/24680145/72f94fa4-1998-11e7-9faa-9b47c3f60695.png)

in the image you can see that the previous screen is gone because it as if i opened another tab and put the scanned number in the address bar.

i cannot control, or do not know how to control the actions performed from interface number 1.
how can i disable it?

**Comment by mcuee** [comment]
Please use pyusb mailing list for technical support.
