### ISSUE TITLE
Problems to connect to NXT brick

### ISSUE THREAD

**Issue by Va2sili** [pyusb/pyusb#188]
I'm using nxt-python 1.2.0, PyBluez 0.22, PyUsb 1.0.0 with Python 2.7 and LibUSB-Win32 1.2.6.0 on Windows 10. I tried to connect to my NXT brick with bluetooth and with usb but I could not get it to connect either way.

With bluetooth, I get the following error:

IOError: a connection attempt failed because the brick didn't reply fast enough
When I execute one of the example programs.

However, python still manages to give the bluetooth adress of the brick (or something else I dont know) using 'host' even if it's not turned on ! nxt.locator.find_one_brick() gives nxt.bluesock.BlueSock object at 0x04481630

When I try to use usb, I get:

USBError: [Errno None] libusb0-dll:err [control_msg] sending control message failed, win error: The specific file cant be found.

nxt.locator.find_one_brick() gives nxt.usbsock.USBSock object at 0x0750ADF0
Can you please help me to connect to the brick with at least one of the both methods. Thanks

**Comment by chibill** [comment]
I don't think pyusb is maintained.... :(

Considering I have had an issue open for a month with no reply.

**Comment by mcuee** [comment]
Maybe you want to try to libusb-1.0 and WinUSB instead of libusb-win32 and try again.

**Comment by Va2sili** [comment]
Okay thank you I will try !

**Comment by mcuee** [comment]
Closing old issues as the OP has not come back with the reply for a long time.
