### ISSUE TITLE
How to read data sent by USB Device over Interrupt endpoint

### ISSUE THREAD

**Issue by RavindraH** [pyusb/pyusb#190]
[readUSBInterrupt.txt](https://github.com/walac/pyusb/files/1324279/readUSBInterrupt.txt)
Hi,

I'm trying to read data that is sent by an USB device over an interrupt endpoint using pyusb. But, I'm seeing that interruptRead() is failing to read any data. I'm not sure if I'm current approach is right for reading data from interrupt endpoint.

I've attached the script for reference. Please let me know in case I'm doing any mistake.

Thanks,
-Ravi

**Comment by mcuee** [comment]
Close this for now.
