### ISSUE TITLE
ImportError: No module named 'usb.core'; 'usb' is not a package

### ISSUE THREAD

**Issue by DouglasLapsley** [pyusb/pyusb#198]
Hi
I installed pyusb-1.0.2 on my raspberry pi (Jessie) with the following:

`pip3 install pyusb`

I import in python with...

`import usb.core`
or just
`import usb`

Either way I get the following error...

ImportError: No module named 'usb.core'; 'usb' is not a package

...when running the following from terminal:

`python3 testusb.py`

It doesn't seem to matter if I run it as sudo or not.

What's really strange is that I managed to get it working the other day, but then I turned on the pi a day later and boom it started failing like this again.

Same happens in Python 2.7 by the way too.

Is this is a bug?  Am I doing something wrong?

Thanks very much!

**Comment by DouglasLapsley** [comment]
I'm such a donkey.  I had called the file usb.py so it was trying to import itself!  Renamed the file and everything works perfectly.

**Comment by MetaFight** [comment]
I'm experiencing this issue.  What did you do to resolve it?

**Comment by mxx-lxg** [comment]
Any fix for this? I'm having the same problem.

**Comment by jonasmalacofilho** [comment]
It seems unlikely that you have the exact same setup as the OP.

Can you please open another issue and provide all relevant context, like OS type and version, Python version, PyUSB version and path (see `pip show`), the error message and the traceback?

Please also include the output of:

```
python -c "import usb; print(usb.__version__)"
```

P.S. Depending on your setup you may need to use `pip3` and `python3` or even specific paths to ensure the desired pip and Python versions are used.

**Comment by mxx-lxg** [comment]
Nevermind. My problem was that my script was called "usb.py" so it tried to import itself.

**Comment by yoyo115956** [comment]
> Nevermind. My problem was that my script was called "usb.py" so it tried to import itself.

Haha, me too. Anyway, thanks a lot!!!

**Comment by redo33** [comment]
I'm very glad that I found this thread. 

Long live. Github !!
