### ISSUE TITLE
USBError: [Errno 13] Access denied (insufficient permissions) macOS High Sierra 

### ISSUE THREAD

**Issue by jkratz55** [pyusb/pyusb#208]
I am unable to get PyUSB working under macOS High Sierra. It seems I can pull information from the device, but I cannot send anything to the USB device. I have libusb and libsub-compat installed via Homebrew. The version of libusb install is 1.0.22. Here is the stacktrace I am seeing when I try to run use PyUSB. I get this stacktrace regardless if I run the Python script with SUDO or without SUDO.

    Traceback (most recent call last):
    File "/Users/jkratz/NFC/src/TRIDResearch.py", line 15, in <module>
        nfcDevice.write(130, 'test')
    File "/Users/jkratz/NFC/venv/lib/python3.7/site-packages/usb/core.py", line 940, in write
        intf, ep = self._ctx.setup_request(self, endpoint)
    File "/Users/jkratz/NFC/venv/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
        return f(self, *args, **kwargs)
    File "/Users/jkratz/NFC/venv/lib/python3.7/site-packages/usb/core.py", line 216, in setup_request
        self.managed_claim_interface(device, intf)
    File "/Users/jkratz/NFC/venv/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
        return f(self, *args, **kwargs)
    File "/Users/jkratz/NFC/venv/lib/python3.7/site-packages/usb/core.py", line 167, in managed_claim_interface
        self.backend.claim_interface(self.handle, i)
    File "/Users/jkratz/NFC/venv/lib/python3.7/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
        _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
    File "/Users/jkratz/NFC/venv/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
        raise USBError(_strerror(ret), ret, _libusb_errno[ret])
    usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

The stacktrace occurs when I attempt to write to the device. My Python code is listed below.

    import usb.core
    import usb.util
    import time

    nfcDevice = usb.core.find(idVendor=0x072f, idProduct=0x2200)

    if nfcDevice is None:
    raise RuntimeError("NFC reader not found")

    print("Found NFC Device")
    print(nfcDevice)
    print()
    print()

    print("Setting configuration")
    nfcDevice.set_configuration()
    print("Configuration set")

    time.sleep(1)

    cfg = nfcDevice.get_active_configuration()

    print("Active configuration")
    print(cfg)

    print("intf")
    intf = cfg[(0,0)]
    print(intf)

    print("Sending command to device")
    time.sleep(1)
    #nfcDevice.write(130, 'test')
    #nfcDevice.write(2, 'test')
    nfcDevice.write(129, 'test')

Here is the output of my device, PyUSB is able to reach the device and pull its information.

    `
    DEVICE ID 072f:2200 on Bus 020 Address 027 =================
    bLength                :   0x12 (18 bytes)
    bDescriptorType        :    0x1 Device
    bcdUSB                 :  0x110 USB 1.1
    bDeviceClass           :    0x0 Specified at interface
    bDeviceSubClass        :    0x0
    bDeviceProtocol        :    0x0
    bMaxPacketSize0        :    0x8 (8 bytes)
    idVendor               : 0x072f
    idProduct              : 0x2200
    bcdDevice              :  0x214 Device 2.14
    iManufacturer          :    0x1 ACS
    iProduct               :    0x2 ACR122U PICC Interface
    iSerialNumber          :    0x0
    bNumConfigurations     :    0x1
    CONFIGURATION 1: 200 mA ==================================
    bLength              :    0x9 (9 bytes)
    bDescriptorType      :    0x2 Configuration
    wTotalLength         :   0x5d (93 bytes)
    bNumInterfaces       :    0x1
    bConfigurationValue  :    0x1
    iConfiguration       :    0x0
    bmAttributes         :   0x80 Bus Powered
    bMaxPower            :   0x64 (200 mA)
        INTERFACE 0: Smart Card ================================
        bLength            :    0x9 (9 bytes)
        bDescriptorType    :    0x4 Interface
        bInterfaceNumber   :    0x0
        bAlternateSetting  :    0x0
        bNumEndpoints      :    0x3
        bInterfaceClass    :    0xb Smart Card
        bInterfaceSubClass :    0x0
        bInterfaceProtocol :    0x0
        iInterface         :    0x0
        ENDPOINT 0x81: Interrupt IN ==========================
        bLength          :    0x7 (7 bytes)
        bDescriptorType  :    0x5 Endpoint
        bEndpointAddress :   0x81 IN
        bmAttributes     :    0x3 Interrupt
        wMaxPacketSize   :    0x8 (8 bytes)
        bInterval        :   0x32
        ENDPOINT 0x2: Bulk OUT ===============================
        bLength          :    0x7 (7 bytes)
        bDescriptorType  :    0x5 Endpoint
        bEndpointAddress :    0x2 OUT
        bmAttributes     :    0x2 Bulk
        wMaxPacketSize   :   0x40 (64 bytes)
        bInterval        :    0x1
        ENDPOINT 0x82: Bulk IN ===============================
        bLength          :    0x7 (7 bytes)
        bDescriptorType  :    0x5 Endpoint
        bEndpointAddress :   0x82 IN
        bmAttributes     :    0x2 Bulk
        wMaxPacketSize   :   0x40 (64 bytes)
        bInterval        :    0x1
    `

Is there something I am doing wrong or does this simply not work with Mac?

**Comment by mcuee** [comment]
Just wondering if you have installed the driver?
https://www.acs.com.hk/en/products/3/acr122u-usb-nfc-reader/

From what I see, the driver acsccid is based on ccid and ccid is based on libusb. So pyusb should work.

You may want to check if you install other drivers or Mac OS X loaded another driver for it. kextstat should be able to list the kernel extensions loaded.

**Comment by jkratz55** [comment]
I downloaded the driver from their site, compiled, and installed it. I am still seeing the same behavior though.

**Comment by mcuee** [comment]
You may want to check if there are other driver which is bound to the device.

**Comment by moliata** [comment]
Same issue over here.

**Comment by mcuee** [comment]
From that thread, it seems to me this has nothing to do with pyusb. If it is an HID device, you can not use libusb/pyusb under Mac OS X since Mac OS X will bind the device to the kernel driver.

**Comment by moliata** [comment]
@mcuee is there any way to unbind the kernel driver from the device?
