### ISSUE TITLE
Weird data when writing to USB Interrupt Endpoint

### ISSUE THREAD

**Issue by HanYangZhao** [pyusb/pyusb#213]
I'm usb this library to write data to and HID usb device. The endpoints uses USB interrupt to communicate. I'm having a problem where the data I'm sending doesn't correspond to what's actually sent when traced from Wireshark.

Here's the endpoint description 

```
write_ep      ENDPOINT 0x5: Interrupt OUT ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x5 OUT
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1
```

Here's my code :
```
msg_1 = \xBF
msg_2 = \xC0
dev.write(write_ep,msg_1,timeout=1000)
dev.write(write_ep,msg_2,timeout=1000)
```
When traced from wireshark I get these

![screenshot from 2018-09-05 11-04-49](https://user-images.githubusercontent.com/4143538/45102429-bb45e500-b0fb-11e8-8c1f-cce1955b2050.png)

And

![screenshot from 2018-09-05 11-05-44](https://user-images.githubusercontent.com/4143538/45102490-dd3f6780-b0fb-11e8-86ab-15376542eca7.png)

I'm not sure where the 0xC2 comes from nor why 0xC0 becomes 0xC3 0x80

Thanks

**Comment by mcuee** [comment]
Do you know the communication protocol of the product? You may want to read the HID spec which may help you understand better HID report format. In the end you still need to know the communication protocol of the device as well.

Ref: https://www.usb.org/hid
https://www.usb.org/sites/default/files/documents/hid1_11.pdf

**Comment by mcuee** [comment]
Please use pyusb mailing list for technical support.
