### ISSUE TITLE
read() takes from 3 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by henfri** [pyusb/pyusb#217]
Hello,

I am trying to get an older code (not developed by myself) to run (https://github.com/smarthomeNG/plugins/blob/master/iaqstick/__init__.py)

I having trouble though at several points and I suspect that it is related to a change in the interface of pyusb.

The first problem was this:
`usb.util.get_string(dev, 0x101, 0x01, 0x409)`
Here get_string was expecting fewer arguments.

I solved this by:
`usb.util.get_string(dev, dev.iManufacturer)`

I hope, this is right.

But I cannot fix this, as I do not undertand it:
`ret = bytes(dev.read(0x81, 0x10, self._intf, 1000))`

self._intf is 0
I get an exception:

> read() takes from 3 to 4 positional arguments but 5 were given

But I see only 4 parameters.
What may be the issue here?

Greetings,
Hendrik

**Comment by ixjlyons** [comment]
The interface kwarg isn't taken by the `read` method anymore https://github.com/pyusb/pyusb/commit/6ead75388434b447a57c44852dac62d40be60861#diff-b5a4f98a864952f0f55d569dd14695b7

So it looks like you can just use:

```python
 ret = bytes(dev.read(0x81, 0x10, 1000))
```

Also note that `read` is a method, so `self` is implicitly passed giving the "5 were given" error.

**Comment by henfri** [comment]
Hello,

thanks a lot. That was quick.
I now get this:

> iaqstick: read - [Errno None] b'could not detach kernel driver from interface 0: No data available.

Do you have an Idea, what the reason could be?

Regards,
Hendrik

**Comment by mcuee** [comment]
Please use pyusb mailing list for technical support.
