### ISSUE TITLE
Before running the code, I need to pull and plug the usb motor once to work

### ISSUE THREAD

**Issue by woshiyushengzhou** [pyusb/pyusb#219]
dear all:
import usb.core
import usb.util
import array

data_list = [0x01,0x01,0x08,0x00,0x00,0x00,0xc1,0x00,0x20,0x23,0xe8,0x03,0x00,0x00,0x03,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00]
my_data = array.array('B',data_list)

dev = usb.core.find(idVendor=1155, idProduct=22352)

if dev is None:
    raise ValueError('Device not found')

if dev.is_kernel_driver_active(0):
    dev.detach_kernel_driver(0)

dev.set_configuration()

cfg = dev.get_active_configuration()
intf = cfg[(0,0)]
ep = usb.util.find_descriptor(
    intf,
    # match the first OUT endpoint
    custom_match = \
    lambda e: \
        usb.util.endpoint_direction(e.bEndpointAddress) == \
        usb.util.ENDPOINT_OUT)

assert ep is not None

ep.write(my_data)
print("has write data...")

The above is my code, I really need your help!

**Comment by mcuee** [comment]
Not a pyusb issue. You need to understand how the device works before using pyusb.

**Comment by mcuee** [comment]
Please use pyusb mailing list for technical support.
