### ISSUE TITLE
Exclusive input mode for a barcode reader on Mac OS X

### ISSUE THREAD

**Issue by poifox** [pyusb/pyusb#222]
I'm trying to get exclusive access from my python program of a barcode reader. I did achieve my goals on linux but Mac OS X refuses to allow me to reserve the device:

This code runs flawlessly on Ubuntu 18.04, under virtualenv setup with Python 3.6, but it doesn't on Mac OS X Mojave, under the "same" virtualenv setup. 

```python
device = usb.core.find(idVendor=0x0519, idProduct=0x2017)
if device.is_kernel_driver_active(0):
	device.detach_kernel_driver(0)
	print("Kernel driver detached")
else:
	print("Kernel driver already detached")
try:
	device.set_configuration()
	device.reset()
	usb.util.claim_interface(device, 0) # error comes from here
	print("Claimed device")
except Exception as e:
	print("Error when claiming device", e)
	sys.exit(1)
# endpoint setup and reading loop...
```

The code runs like a charm on Ubuntu, but fails on Mac OS.

```shell
[Errno 13] Access denied (insufficient permissions)
```

The fix on Ubuntu is to add permission directive in `/etc/udev/rules.d/` but I can't seem to find the equivalent fix for Mac OS. Any pointers are greatly appreciated.

**Comment by mcuee** [comment]
No way on Mac OS. You need to create a codeless kext and get a signed package from Apple. So just forget about it.

Not an pyusb issue.
