### ISSUE TITLE
`USBError` should be in `__all__`

### ISSUE THREAD

**Issue by mcondarelli** [pyusb/pyusb#228]
Thanks for this package.

Just a nitpick:
```python
    from usb import USBError
```
results in a warning in PyCharm because:

    'USBError' is not declared in __all__ less... (Ctrl+F1) 
    Inspection info: This inspection warns if a protected member is accessed outside the class, a descendant of the class where it's defined or a module.

I think this should be included as it's quite common to try yo handle USB errors (especially disconnects!)

**Comment by mcuee** [comment]
Patches welcome.
