### ISSUE TITLE
Installation Not Running - Error in setup.py

### ISSUE THREAD

**Issue by RedHoodedWraith** [pyusb/pyusb#229]
Whenever I try to install via PIP, I get the following error message:
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-XNZPQu/pyusb/`

Then when I manually downloaded the repository and tried to run `setup.py`, I kept getting this error:
```
Traceback (most recent call last):
  File "./setup.py", line 18, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```

I couldn't see any references for a library called "setuptools" being a prerequisite and if so I am unsure how to install it. Alternatively, the PIP install should have happened successfully unless I'm missing something. 

If it helps, I am running Linux Mint 19.

-Rowan

**Comment by GhostofGoes** [comment]
If you're building it directly, you need `setuptools` installed.

```bash
sudo apt update
sudo apt install python3-setuptools
```

**Comment by alfrede** [comment]
Hi Rowan, 

i use Mint 19, too and do the same: 
sudo apt update
sudo apt install python3-setuptools

but it doesn't work. What the solution by me was :

sudo apt install python3-pip
and then 
pip3 install pyusb

Greetz
Alfrede
