### ISSUE TITLE
libUsb

### ISSUE THREAD

**Issue by Daygrie** [pyusb/pyusb#243]
```
import usb.backend.libusb1
import usb.core

backend = usb.backend.libusb1.get_backend(find_library=lambda x: "libusb-1.0.dll")
dev = usb.core.find(idVendor=0x067b, idProduct=0x2303,backend=backend)
```

Why using this code Python prints: No Backend Avaible? Ty
I am on Windows Machine :( and i have dll file in the project directory.
Python prints error though I  don't insert only file name but though I insert the full path

**Comment by ixjlyons** [comment]
Maybe this thread/comment will help: https://github.com/pyusb/pyusb/issues/120#issuecomment-368758659

**Comment by Daygrie** [comment]
ty

**Comment by Daygrie** [comment]
ty
