### ISSUE TITLE
usb.core.find device object how can i write(No response from developer)

### ISSUE THREAD

**Issue by premananda8** [pyusb/pyusb#276]
after getting device object i'm trying to write like this but getting error
dev.write(endpoint=0x00,data=[0x7E,0xA1,0x81, 0x83,0x81, 0x40,0x00,0x01, 0x41], timeout=4000)

error as:
 File "C:\Users\Lab7\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\core.py", line 231, in get_interface_and_endpoint
    raise ValueError('Invalid endpoint address ' + hex(endpoint_address))
ValueError: Invalid endpoint address 0x0

**Comment by ixjlyons** [comment]
I don't think you can use `write` for endpoint 0. Try `dev.ctrl_transfer` instead?

**Comment by mcuee** [comment]
This is not an issue. Please use mailing list for technical support.
