### ISSUE TITLE
Emulating a USB device

### ISSUE THREAD

**Issue by raviv** [pyusb/pyusb#283]
Can I create a "virtual USB device" with PyUSB?
I want to create a device that appears as a USB webcam to the OS.

**Comment by jonasmalacofilho** [comment]
No, that's not possible with PyUSB or its backends.

I haven't looked into this in much detail, but apparently you can use USB over IP to emulate devices.  You can also use programmable and/or specialized hardware.[¹](https://www.devalias.net/devalias/2018/05/13/usb-reverse-engineering-down-the-rabbit-hole/#where-next)

And it might also be possible to achieve this with a dummy kernel driver (I'm thinking about Linux here).
