### ISSUE TITLE
Bulk out modifies data

### ISSUE THREAD

**Issue by SECimon** [pyusb/pyusb#293]
Hi,

when sending data to a device via bulk out transfer, the data seems to be modified.
It's not possible to send a byte greater than 0x7F, otherwise it gets modified. 
I was searching for the issue for days until I tried the same with LibUsbDotNet and had no problems. So the "same" code/commands are working with LibUsbDotNet, but not with pyusb.

I don't know which backend I am using, can someone tell me how to get that?

Here is a minimal code to reproduce the issue:

``` bash
import usb.core
import usb.util
import usb.control

def main():
    dev = usb.core.find(idVendor=0x0000, idProduct=0x0000) # I think the specific device doesn't really matter
    dev.set_configuration()
    cfg = dev.get_active_configuration()
    bulkOut=  cfg[(1, 0)][0]

    command = '\x01\x20\x30\x70\x7F\x80\x01\x20\x30\xFF'
    bulkOut.write(command)

if __name__ == "__main__":
    main()
```

The output captured with Wireshark is:
\x01\x20\x30\x70\x7F **\xC2\x80** \x01\x20\x30 **\xC3\xBF**

**Comment by jonasmalacofilho** [comment]
Python 3 uses Unicode strings.

This means that in

```py
command = '\x01\x20\x30\x70\x7F\x80\x01\x20\x30\xFF'
```

both `\x80` and `\xff`are interpreted by Python as Unicode *code-points* 0x80 and 0xff.¹

Because of this, you actually want to use a `bytes` literal:

```py
command = b'\x01\x20\x30\x70\x7F\x80\x01\x20\x30\xFF'
```

---

¹ https://docs.python.org/3/reference/lexical_analysis.html#literals
