### ISSUE TITLE
Two identical hid devices

### ISSUE THREAD

**Issue by WanManito** [pyusb/pyusb#321]
Hello, I want to query two hid devices with the same [idvendor] and [idproduct]
Through the following code, but it doesn't seem to work
![image](https://user-images.githubusercontent.com/26118508/91965249-ce1f3e80-ed42-11ea-95f0-457162148cde.png)
I don't know how to operate to get two identical hid devices

**Comment by jonasmalacofilho** [comment]
`usb.core.find(find_all=True, ...)` returns an iterator of `Device` instances, so you probably want to loop over it.
