### ISSUE TITLE
OSError: exception: access violation writing 0x0000000000000024

### ISSUE THREAD

**Issue by WanManito** [pyusb/pyusb#322]
![image](https://user-images.githubusercontent.com/26118508/92215185-fcc62200-eec6-11ea-8a50-86c84bba5019.png)
![image](https://user-images.githubusercontent.com/26118508/92215227-0bacd480-eec7-11ea-88e5-c01c0f831742.png)
hello，I don't know why I print this exception

**Comment by mcuee** [comment]
Did you try the latest libusb Windows 1.0.23 release and latest pyusb?

**Comment by WanManito** [comment]
@mcuee 
![image](https://user-images.githubusercontent.com/26118508/92559512-4f2a8880-f2a3-11ea-9025-834dcafd98aa.png)
![image](https://user-images.githubusercontent.com/26118508/92559574-6c5f5700-f2a3-11ea-906a-abb1ffb79767.png)
I think I should use the latest library

**Comment by mcuee** [comment]
No you are not using the latest pyusb. You need to download latest git repo and install by yourself, not using pip.

**Comment by mcuee** [comment]
Your issue may already got fixed in latest git.
https://github.com/pyusb/pyusb/issues/288

**Comment by WanManito** [comment]
@mcuee 
![image](https://user-images.githubusercontent.com/26118508/92561228-67e86d80-f2a6-11ea-987f-cc7d71721d36.png)
I have solved the problem by installing Git, thank you

**Comment by WanManito** [comment]
@mcuee Hello, I found a bug in the new version. In 1.0.2, I called“ usb.util.dispose_ resources( self.dev ）”Release the resources and connect again next time. There is no problem
When I update to the latest version of GIT, I still call "dispose" for the same code_ Resources ", which is then triggered in the child thread“ self.dev.read (self.__ Again, I reported an exception in 64“ self.dev.set_ Configuration() "is stuck and cannot be connected,,,
Again, I didn't change a single line of code, just changed the version of the library

**Comment by WanManito** [comment]
The same code, just switching to the latest version, causes an exception

**Comment by jonasmalacofilho** [comment]
> Again, I didn't change a single line of code, just changed the version of the library

Can you `git bisect` to a specific commit that causes this problem?

**Comment by jonasmalacofilho** [comment]
Note that there's already a specific issue for the different behavior under git/1.1.0: #325.

**Comment by jonasmalacofilho** [comment]
Problem has been solved, as mentioned in #325.
