### ISSUE TITLE
usb.core.find Running time

### ISSUE THREAD

**Issue by WanManito** [pyusb/pyusb#326]
![image](https://user-images.githubusercontent.com/26118508/93035112-b6af5200-f66e-11ea-9bf7-577aa44e4319.png)
![image](https://user-images.githubusercontent.com/26118508/93035141-c890f500-f66e-11ea-99a9-1181bcf16160.png)
I seem to feel that the "find" function takes more time to update to the latest version. I don't know if it's my illusion

**Comment by jonasmalacofilho** [comment]
Cannot reproduce on my (real) Linux machine:

```
$ ./timeit.sh
Using PyUSB 1.0.2
50000000 loops, best of 5: 4.64 nsec per loop
```

```
$ ./timeit.sh
Using PyUSB 1.1.0.post2+g6321b838432f
50000000 loops, best of 5: 4.63 nsec per loop
```

I will try this again on a (real) Windows machine and a couple of other Linux machines.

At the same time, please also use the script bellow to check whether it's just your "illusion" (run it once under PyUSB 1.0.2, and another time under 1.1.0 or git).

---

```
$ cat timeit.sh
#!/bin/bash

python -c "import usb; print(f'Using PyUSB {usb.__version__}')"
python -m timeit -s "import usb; list(usb.core.find(find_all=True))"
```

**Comment by WanManito** [comment]
![image](https://user-images.githubusercontent.com/26118508/93407930-ef953400-f8c5-11ea-94a7-15dac4daaf55.png)
It's all of a sudden normal again, I don't know what's going on
