### ISSUE TITLE
Clean up pyusb website: https://pyusb.github.io/pyusb/

### ISSUE THREAD

**Issue by mcuee** [pyusb/pyusb#327]
A few clean up is needed. [Edit: Done]

1) libusb-1.0 link needs to change to "https://libusb.info/"
2) libusbx needs to be removed.
3) better to remove openusb as well.
4) libusb-win32 webpage needs to change to: "https://github.com/mcuee/libusb-win32"

**Comment by mcuee** [comment]
I am not familiar with github pages yet. It seems to be a special repo and I can not see it.

For libusb, there is a git repo under libusb organization.
https://github.com/libusb/libusb.github.com

**Comment by mcuee** [comment]
Another thing, it still mentions Python 2.4. I am not so sure if we want to support that. Probably we can change the sentence to "but most things should still work with Python 2.7".

**Comment by jonasmalacofilho** [comment]
Agreed, it needs some cleaning up.  It and the README in this repository also need to more closely match.

I'll do that in the next few days.

**Comment by clach04** [comment]
> 
> 
> I am not familiar with github pages yet. It seems to be a special repo and I can not see it.
> 
> For libusb, there is a git repo under libusb organization.
> https://github.com/libusb/libusb.github.com

Content in gh-pages branch https://github.com/pyusb/pyusb/tree/gh-pages is where the site https://pyusb.github.io/pyusb/ gets its source. PRs can be opened against that branch :)

**Comment by mcuee** [comment]
I see. Thanks. I have just updated a bit on the github pages.

**Comment by jonasmalacofilho** [comment]
Thanks!

**Comment by mcuee** [comment]
Close this for now. We can continue to update the git pages.
