### ISSUE TITLE
Installing build dependencies ... error

### ISSUE THREAD

**Issue by edoardo73** [pyusb/pyusb#339]
OS: Windows 7 Pro SP1
`Python 3.7.9`
`pip 20.3.1 from c:\python37\lib\site-packages\pip (python 3.7)`
`setuptools 50.3.2 from c:\python37\lib\site-packages (Python 3.7)`

Hello,

I was installing pyusb:

`pip install pyusb`

but it returned:

> ```
> Collecting pyusb
>   Using cached pyusb-1.1.0.tar.gz (78 kB)
>   Installing build dependencies ... error
>   ERROR: Command errored out with exit status 1:
>    command: 'c:\python37\python.exe' 'c:\python37\lib\site-packages\pip' install
>  --ignore-installed --no-user --prefix 'C:\Users\edoardo\AppData\Local\Temp\pip-
> build-env-elp7iyz5\overlay' --no-warn-script-location --no-binary :none: --only-
> binary :none: -i https://pypi.org/simple -- 'setuptools>=30.3.0' wheel setuptools_scm
>        cwd: None
>   Complete output (42 lines):
>   Traceback (most recent call last):
>     File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
>       "__main__", mod_spec)
>     File "c:\python37\lib\runpy.py", line 85, in _run_code
>       exec(code, run_globals)
>     File "c:\python37\lib\site-packages\pip\__main__.py", line 26, in <module>     sys.exit(_main())
>     File "c:\python37\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
>       command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
>     File "c:\python37\lib\site-packages\pip\_internal\commands\__init__.py", line 105, in create_command
>       module = importlib.import_module(module_path)
>     File "c:\python37\lib\importlib\__init__.py", line 127, in import_module
>       return _bootstrap._gcd_import(name[level:], package, level)
>     File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>     File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>     File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>     File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>     File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> 
>     File "c:\python37\lib\site-packages\pip\_internal\commands\install.py", line  17, in <module>
>       from pip._internal.cli.req_command import RequirementCommand, with_cleanup
> 
>     File "c:\python37\lib\site-packages\pip\_internal\cli\req_command.py", line 18, in <module>
>       from pip._internal.index.collector import LinkCollector
>     File "c:\python37\lib\site-packages\pip\_internal\index\collector.py", line 14, in <module>
>       from pip._vendor import html5lib, requests
>     File "c:\python37\lib\site-packages\pip\_vendor\requests\__init__.py", line 125, in <module>
>       from . import utils
>     File "c:\python37\lib\site-packages\pip\_vendor\requests\utils.py", line 25,  in <module>
>       from . import certs
>     File "c:\python37\lib\site-packages\pip\_vendor\requests\certs.py", line 15,  in <module>
>       from pip._vendor.certifi import where
>     File "c:\python37\lib\site-packages\pip\_vendor\certifi\__init__.py", line 1, in <module>
>       from .core import contents, where
>     File "c:\python37\lib\site-packages\pip\_vendor\certifi\core.py", line 12, in <module>
>       from importlib.resources import path as get_path, read_text
>     File "c:\python37\lib\importlib\resources.py", line 11, in <module>
>       from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
> 
>     File "c:\python37\lib\site-packages\typing.py", line 1357, in <module>
>       class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
>     File "c:\python37\lib\site-packages\typing.py", line 1005, in __new__
>       self._abc_registry = extra._abc_registry
>   AttributeError: type object 'Callable' has no attribute '_abc_registry'
>   ----------------------------------------
> ERROR: Command errored out with exit status 1: 'c:\python37\python.exe' 'c:\pyth
> on37\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Us
> ers\edoardo\AppData\Local\Temp\pip-build-env-elp7iyz5\overlay' --no-warn-script-
> location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- '
> setuptools>=30.3.0' wheel setuptools_scm Check the logs for full command output.
> ```

I tried to search online if a similar issue was already brought up, but I found nothing.
Could you please explain where is the problem?

Thank you
Cheers,
Edo

**Comment by jonasmalacofilho** [comment]
Your environment's `pip` is broken, which doesn't relate to PyUSB, but the following should help:

https://stackoverflow.com/questions/55833509/attributeerror-type-object-callable-has-no-attribute-abc-registry
