### ISSUE TITLE
pyusb and libusb 1.0.24 macOS issue

### ISSUE THREAD

**Issue by mcuee** [pyusb/pyusb#342]
Ref: https://github.com/libusb/libusb/issues/824

From libusb developer Chris.
> Ok, finally figured this out. The problem is that pyusb is holding references to libusb devices after calling `libusb_exit()`. When `libusb_unref_device()` is called later, one or more of these devices are still pointing to `darwin_cached_devices` and that is how it is getting modified back to a non-NULL value. A simple reproducer in C:

**Comment by jonasmalacofilho** [comment]
Apparently it was [already fixed in 1.1.0](https://github.com/libusb/libusb/issues/824#issuecomment-743974400), probably by #227.

**Comment by mcuee** [comment]
Great. This was fast.
