### ISSUE TITLE
usb.core.USBError: [Errno 19] No such device (it may have been disconnected)

### ISSUE THREAD

**Issue by WanManito** [pyusb/pyusb#348]
pyusb==1.1.0

When a HID device has two interfaces, one is the analog keyboard output, the other is the normal communication channel, this API can't work normally. When I switch to the normal interface, I will prompt the title error. This problem can be perfectly solved in Java, Android and C #. I don't know if it can be solved in this API, thank you

**Comment by WanManito** [comment]
2020-12-29 10:57:32,516 DEBUG:usb.backend.libusb1:_LibUSB.__init__(<WinDLL 'C:\Windows\system32\libusb-1.0.dll', handle 7ffccc380000 at 0x1b45aeff7c8>)
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.000000] [000046a0] libusb: debug [libusb_init] created default context
[ 0.000000] [000046a0] libusb: debug [libusb_init] libusb v1.0.23.11397
[ 0.000000] [000046a0] libusb: debug [windows_init_dlls] Will use CancelIoEx for I/O cancellation
[ 0.000998] [000046a0] libusb: debug [get_windows_version] Windows 10 64-bit
[ 0.000998] [000046a0] libusb: debug [windows_init_clock] hires timer available (Frequency: 10000000 Hz)
[ 0.000998] [000046a0] libusb: debug [windows_init_clock] timer thread will run on core #0
[ 0.001994] [000046a0] libusb: debug [htab_create] using 1021 entries hash table
[ 0.011969] [000046a0] libusb: info [winusbx_init] libusbK DLL is not available, will use native WinUSB
[ 0.013964] [000046a0] libusb: debug [winusbx_init] initalized sub API libusbK
[ 0.014968] [000046a0] libusb: debug [winusbx_init] initalized sub API libusb0
[ 0.014968] [000046a0] libusb: debug [winusbx_init] initalized sub API WinUSB
[ 0.016954] [000046a0] libusb: info [windows_init] UsbDk backend is not available
[ 0.016954] [000046a0] libusb: debug [usbi_add_pollfd] add fd 0 events 1
2020-12-29 10:57:32,534 INFO:usb.core:find(): using backend "usb.backend.libusb1"
2020-12-29 10:57:32,535 DEBUG:usb.backend.libusb1:_LibUSB.enumerate_devices()
[ 0.017952] [000046a0] libusb: debug [libusb_get_device_list]
[ 0.035904] [000046a0] libusb: debug [winusb_get_device_list] allocating new device for session [5F]
[ 0.035904] [000046a0] libusb: debug [winusb_get_device_list] allocating new device for session [60]
[ 0.036900] [000046a0] libusb: debug [winusb_get_device_list] allocating new device for session [61]
[ 0.036900] [000046a0] libusb: debug [get_api_type] driver(s): plser
[ 0.036900] [000046a0] libusb: debug [get_api_type] upper filter driver(s): serenum
[ 0.036900] [000046a0] libusb: debug [winusb_get_device_list] allocating new device for session [25]
[ 0.037897] [000046a0] libusb: debug [get_api_type] driver(s): BTHUSB
[ 0.037897] [000046a0] libusb: debug [get_api_type] lower filter driver(s): ibtusb
[ 0.037897] [000046a0] libusb: debug [winusb_get_device_list] allocating new device for session [3F]
[ 0.038895] [000046a0] libusb: debug [get_api_type] driver(s): AX88772
[ 0.038895] [000046a0] libusb: debug [winusb_get_device_list] allocating new device for session [45]
[ 0.039893] [000046a0] libusb: debug [get_api_type] driver(s): usbccgp
[ 0.039893] [000046a0] libusb: debug [get_api_type] matched driver name against Composite API
[ 0.039893] [000046a0] libusb: debug [winusb_get_device_list] allocating new device for session [46]
[ 0.039893] [000046a0] libusb: debug [get_api_type] driver(s): usbccgp
[ 0.040892] [000046a0] libusb: debug [get_api_type] matched driver name against Composite API
[ 0.040892] [000046a0] libusb: debug [winusb_get_device_list] allocating new device for session [47]
[ 0.040892] [000046a0] libusb: debug [get_api_type] driver(s): WUDFRd
[ 0.040892] [000046a0] libusb: debug [get_api_type] lower filter driver(s): WinUsb
[ 0.041889] [000046a0] libusb: debug [get_api_type] matched lower filter driver name against WinUSB
[ 0.041889] [000046a0] libusb: debug [winusb_get_device_list] allocating new device for session [48]
[ 0.042885] [000046a0] libusb: debug [get_api_type] driver(s): HidUsb
[ 0.042885] [000046a0] libusb: debug [get_api_type] matched driver name against HID API
[ 0.043885] [000046a0] libusb: debug [winusb_get_device_list] allocating new device for session [49]
[ 0.043885] [000046a0] libusb: debug [enumerate_hcd_root_hub] assigning HCD 'PCI\VEN_8086&DEV_9D2F&SUBSYS_16041D72&REV_21\3&11583659&0&A0' bus number 1
[ 0.047872] [000046a0] libusb: debug [winusb_get_device_list] found existing device for session [5F]
[ 0.047872] [000046a0] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.047872] [000046a0] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 41 bytes)
[ 0.048868] [000046a0] libusb: debug [init_device] (bus: 1, addr: 13, depth: 2, port: 4): 'USB\VID_0BDA&PID_5411\6&191677B0&1&4'
[ 0.049869] [000046a0] libusb: debug [winusb_get_device_list] found existing device for session [25]
[ 0.049869] [000046a0] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.049869] [000046a0] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 39 bytes)
[ 0.049869] [000046a0] libusb: debug [init_device] (bus: 1, addr: 14, depth: 3, port: 1): 'USB\VID_067B&PID_23C3\DLAZB19C116'
[ 0.050863] [000046a0] libusb: debug [winusb_get_device_list] found existing device for session [60]
[ 0.050863] [000046a0] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.051862] [000046a0] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 25 bytes)
[ 0.051862] [000046a0] libusb: debug [init_device] (bus: 1, addr: 1, depth: 1, port: 1): 'USB\VID_05E3&PID_0608\5&E4A4C6&0&1'
[ 0.052862] [000046a0] libusb: debug [winusb_get_device_list] found existing device for session [45]
[ 0.052862] [000046a0] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.052862] [000046a0] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 39 bytes)
[ 0.052862] [000046a0] libusb: debug [init_device] (bus: 1, addr: 6, depth: 2, port: 1): 'USB\VID_0B95&PID_772B\C1A896'
[ 0.053855] [000046a0] libusb: debug [init_device] (bus: 1, addr: 0, depth: 0, port: 0): 'USB\ROOT_HUB30\4&F6625D6&0&0'
[ 0.053855] [000046a0] libusb: debug [winusb_get_device_list] found existing device for session [47]
[ 0.054854] [000046a0] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.054854] [000046a0] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 637 bytes)
[ 0.054854] [000046a0] libusb: debug [init_device] (bus: 1, addr: 3, depth: 1, port: 5): 'USB\VID_04F2&PID_B5A3\5&E4A4C6&0&5'
[ 0.055849] [000046a0] libusb: debug [winusb_get_device_list] found existing device for session [46]
[ 0.055849] [000046a0] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.055849] [000046a0] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 66 bytes)
[ 0.055849] [000046a0] libusb: debug [init_device] (bus: 1, addr: 19, depth: 2, port: 3): 'USB\VID_03EB&PID_2421\123123123123'
[ 0.056847] [000046a0] libusb: debug [winusb_get_device_list] found existing device for session [48]
[ 0.056847] [000046a0] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.056847] [000046a0] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 62 bytes)
[ 0.056847] [000046a0] libusb: debug [init_device] (bus: 1, addr: 4, depth: 1, port: 6): 'USB\VID_04F3&PID_0C1A\5&E4A4C6&0&6'
[ 0.057844] [000046a0] libusb: debug [winusb_get_device_list] found existing device for session [49]
[ 0.059840] [000046a0] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.060838] [000046a0] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 34 bytes)
[ 0.060838] [000046a0] libusb: debug [init_device] (bus: 1, addr: 2, depth: 1, port: 4): 'USB\VID_1EA7&PID_10C0\5&E4A4C6&0&4'
[ 0.061834] [000046a0] libusb: debug [discovered_devs_append] need to increase capacity
[ 0.061834] [000046a0] libusb: debug [winusb_get_device_list] found existing device for session [3F]
[ 0.062833] [000046a0] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.062833] [000046a0] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 177 bytes)
[ 0.062833] [000046a0] libusb: debug [init_device] (bus: 1, addr: 5, depth: 1, port: 7): 'USB\VID_8087&PID_0A2B\5&E4A4C6&0&7'
[ 0.066821] [000046a0] libusb: debug [winusb_get_device_list] unlisted ancestor for 'HID\ELAN2301&COL01\5&16BE506D&0&0000' (non USB HID, newly connected, etc.) - ignoring
[ 0.066821] [000046a0] libusb: debug [winusb_get_device_list] setting HID interface for [49]:
[ 0.067820] [000046a0] libusb: debug [set_hid_interface] interface[0] = \\.\HID#VID_1EA7&PID_10C0#6&46BDC38&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.067820] [000046a0] libusb: debug [winusb_get_device_list] unlisted ancestor for 'HID\ELAN2301&COL02\5&16BE506D&0&0001' (non USB HID, newly connected, etc.) - ignoring
[ 0.068816] [000046a0] libusb: debug [winusb_get_device_list] unlisted ancestor for 'HID\ELAN2301&COL03\5&16BE506D&0&0002' (non USB HID, newly connected, etc.) - ignoring
[ 0.068816] [000046a0] libusb: debug [winusb_get_device_list] unlisted ancestor for 'HID\WSTADEF\3&2DA71541&0&0000' (non USB HID, newly connected, etc.) - ignoring
[ 0.068816] [000046a0] libusb: debug [winusb_get_device_list] unlisted ancestor for 'HID\ELAN2301&COL04\5&16BE506D&0&0003' (non USB HID, newly connected, etc.) - ignoring
[ 0.070810] [000046a0] libusb: debug [winusb_get_device_list] setting composite interface for [46]:
[ 0.070810] [000046a0] libusb: debug [set_composite_interface] interface[0] = \\.\HID#VID_03EB&PID_2421&MI_00#8&6AEAA9B&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.096741] [000046a0] libusb: debug [winusb_get_device_list] setting composite interface for [46]:
[ 0.112698] [000046a0] libusb: debug [set_composite_interface] interface[1] = \\.\HID#VID_03EB&PID_2421&MI_01#8&1E7236E0&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}#KBD
2020-12-29 10:57:32,632 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>)
[ 0.115691] [000046a0] libusb: debug [libusb_get_device_descriptor]
2020-12-29 10:57:32,634 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x000001B45C8CDE48>)
[ 0.116688] [000046a0] libusb: debug [libusb_get_device_descriptor]
2020-12-29 10:57:32,635 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>)
[ 0.118684] [000046a0] libusb: debug [libusb_get_device_descriptor]
2020-12-29 10:57:32,637 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x000001B45C8CDF08>)
[ 0.123670] [000046a0] libusb: debug [libusb_get_device_descriptor]
2020-12-29 10:57:32,645 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x000001B45C8CDB48>)
[ 0.131647] [000046a0] libusb: debug [libusb_get_device_descriptor]
2020-12-29 10:57:32,674 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x000001B45C8CDF48>)
[ 0.173535] [000046a0] libusb: debug [libusb_get_device_descriptor]
2020-12-29 10:57:32,696 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>)
[ 0.182514] [000046a0] libusb: debug [libusb_get_device_descriptor]
[ 0.184506] [000046a0] libusb: debug [libusb_unref_device] destroy device 1.14
[ 0.190490] [000046a0] libusb: debug [libusb_unref_device] destroy device 1.13
[ 0.190490] [000046a0] libusb: debug [libusb_unref_device] destroy device 1.6
[ 0.191488] [000046a0] libusb: debug [libusb_unref_device] destroy device 1.3
[ 0.192485] [000046a0] libusb: debug [libusb_unref_device] destroy device 1.4
[ 0.193494] [000046a0] libusb: debug [libusb_unref_device] destroy device 1.2
[ 0.193494] [000046a0] libusb: debug [libusb_unref_device] destroy device 1.5
<class 'usb.core.Device'>
2020-12-29 10:57:32,711 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>, 0)
[ 0.195477] [000046a0] libusb: debug [libusb_get_config_descriptor] index 0
<class 'usb.core.Configuration'>
2020-12-29 10:57:32,737 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>, 0)
[ 0.221421] [000046a0] libusb: debug [libusb_get_config_descriptor] index 0
2020-12-29 10:57:32,740 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>, 0, 0, 0)
2020-12-29 10:57:32,740 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>, 0)
[ 0.224400] [000046a0] libusb: debug [libusb_get_config_descriptor] index 0
<generator object find_descriptor.<locals>.desc_iter at 0x000001B45C87DEC8>
2020-12-29 10:57:32,742 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>, 0, 0, 0, 0)
2020-12-29 10:57:32,743 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>, 0, 0, 0)
2020-12-29 10:57:32,743 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>, 0)
[ 0.226395] [000046a0] libusb: debug [libusb_get_config_descriptor] index 0
2020-12-29 10:57:32,744 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>, 1, 0, 0, 0)
2020-12-29 10:57:32,745 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>, 0, 0, 0)
2020-12-29 10:57:32,745 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>, 0)
[ 0.229386] [000046a0] libusb: debug [libusb_get_config_descriptor] index 0
2020-12-29 10:57:32,749 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>, 0, 0, 0, 0)
2020-12-29 10:57:32,759 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>, 0, 0, 0)
2020-12-29 10:57:32,761 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>, 0)
[ 0.244346] [000046a0] libusb: debug [libusb_get_config_descriptor] index 0
2020-12-29 10:57:32,762 DEBUG:usb.backend.libusb1:_LibUSB.open_device(<usb.backend.libusb1._Device object at 0x000001B45AEB1108>)
[ 0.246341] [000046a0] libusb: debug [libusb_open] open 1.19
[ 0.255317] [000046a0] libusb: warning [hid_open] could not open HID device in R/W mode (keyboard or mouse?) - trying without
[ 0.256320] [000046a0] libusb: error [hid_open] could not open device \\.\USB#VID_03EB&PID_2421#123123123123#{A5DCBF10-6530-11D2-901F-00C04FB951ED} (interface 1): [2] 系统找不到指定的文件。
[ 0.256320] [000046a0] libusb: debug [libusb_open] open 1.19 returns -4
Traceback (most recent call last):
  File "D:\Python\Python37\lib\site-packages\usb\core.py", line 234, in get_interface_and_endpoint
    return self._ep_info[endpoint_address]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "usb_utils.py", line 71, in <module>
    outPoint.write(msg) 
  File "D:\Python\Python37\lib\site-packages\usb\core.py", line 406, in write
    return self.device.write(self, data, timeout)
  File "D:\Python\Python37\lib\site-packages\usb\core.py", line 974, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "D:\Python\Python37\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "D:\Python\Python37\lib\site-packages\usb\core.py", line 226, in setup_request
    intf, ep = self.get_interface_and_endpoint(device, endpoint_address)
  File "D:\Python\Python37\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "D:\Python\Python37\lib\site-packages\usb\core.py", line 236, in get_interface_and_endpoint
    for intf in self.get_active_configuration(device):
  File "D:\Python\Python37\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "D:\Python\Python37\lib\site-packages\usb\core.py", line 247, in get_active_configuration
    self.managed_open()
  File "D:\Python\Python37\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "D:\Python\Python37\lib\site-packages\usb\core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "D:\Python\Python37\lib\site-packages\usb\_debug.py", line 62, in do_trace
    return f(*args, **named_args)
  File "D:\Python\Python37\lib\site-packages\usb\backend\libusb1.py", line 804, in open_device
    return _DeviceHandle(dev)
  File "D:\Python\Python37\lib\site-packages\usb\backend\libusb1.py", line 652, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "D:\Python\Python37\lib\site-packages\usb\backend\libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 19] No such device (it may have been disconnected)
[ 0.369013] [000046a0] libusb: debug [libusb_unref_device] destroy device 1.19
[ 0.370012] [000046a0] libusb: debug [libusb_unref_device] destroy device 1.1
[ 0.370012] [000046a0] libusb: debug [libusb_unref_device] destroy device 1.0
2020-12-29 10:57:32,889 DEBUG:usb.backend.libusb1:_LibUSB._finalize_object()
[ 0.372007] [000046a0] libusb: debug [libusb_exit]
[ 0.373005] [000046a0] libusb: debug [libusb_exit] destroying default context
[ 0.373005] [000046a0] libusb: debug [usbi_remove_pollfd] remove fd 0
[ 0.375996] [00003e64] libusb: debug [windows_clock_gettime_threaded] timer thread quitting

**Comment by WanManito** [comment]
![image](https://user-images.githubusercontent.com/26118508/103255673-28649f00-49c5-11eb-9bc7-862f438f3917.png)
interface[0] It is available, but how do I get it

**Comment by WanManito** [comment]
import usb.core
import usb.util
import time


import platform

# find our device
dev = usb.core.find(idVendor=0x03EB, idProduct=0x2421)  

# was it found?
if dev is None:
    raise ValueError('Device not found')

if platform.system().lower() == 'linux':
    if dev.is_kernel_driver_active(0):
        dev.detach_kernel_driver(0)  

# set the active configuration. With no arguments, the first
# configuration will be the active one
# dev.set_configuration()

# get an endpoint instance
# configuration = dev.get_active_configuration()
configuration = dev[0]

cfg_ = configuration[(0, 0)]
# alt = usb.util.find_descriptor(cfg_, find_all=True, bInterfaceNumber=1)
# print(alt)

# 0x2 
outPoint = usb.util.find_descriptor(
    cfg_,
    # match the first OUT endpoint
    custom_match=lambda e: usb.util.endpoint_direction(e.bEndpointAddress) == usb.util.ENDPOINT_OUT)

# 0x81 
inPoint = usb.util.find_descriptor(
    cfg_,
    # match the first IN endpoint
    custom_match=lambda e: usb.util.endpoint_direction(e.bEndpointAddress) == usb.util.ENDPOINT_IN)

# assert outPoint, inPoint is not None

outPoint.write("msg")  

read = inPoint.read(64)

**Comment by jonasmalacofilho** [comment]
Your mileage will vary with HIDs: [Does libusb support USB HID devices?](https://github.com/libusb/libusb/wiki/FAQ#does-libusb-support-usb-hid-devices).

**Comment by WanManito** [comment]
It should be supported, because libusb is also used in Java and C #, and now it is "debug [set]_ composite_ interface] interface[0] = \\.\HID#VID_ 03EB&amp;PID_ 2421&amp;MI_ 00#8&amp;6AEAA9B&amp;0&amp;0000#{4D1E55B2-F16F-11CF-88CB-001111000030} [ 0.096741] [000046a0] libusb: debug [winusb_ get_ device_ list] setting composite interface for [46]: [ 0.112698] [000046a0] libusb: debug [set_ composite_ interface] interface[1] = \\.\HID#VID_ 03EB&amp;PID_ 2421&amp;MI_ 01#8&amp;1E7236E0&amp;0&amp;0000#{4D1E55B2-F16F-11CF-88CB-001111000030}#KBD"，
"Interface [0]" is what I want @jonasmalacofilho

**Comment by WanManito** [comment]
In other platforms, it only distinguishes between keyboard mode and communication mode, that is, which channel can be used in the interface. It can be seen in the debug log that it can distinguish between the two channels, which can be realized by logic

**Comment by jonasmalacofilho** [comment]
> "Interface [0]" is what I want @jonasmalacofilho

@WanManito this is your seventh not-really-an-issue issue here.  I'm sorry, but I'm not consulting for you.  Please pinpoint a specific and, preferably, reproduceable (with common devices) problem; if a reproduceable example is not possible, please show real/practical C code using libusb that works and that shows what exactly is PyUSB doing wrong.

---

P.S.  And you don't even appear to be using PyUSB for a free/open source software project!

**Comment by WanManito** [comment]
We use Cpython hidapi instead

**Comment by WanManito** [comment]
This is the implementation of "Cpython hidapi", which can distinguish different channels of the same device. I've tried pyusb for a long time, but I haven't found a way
![image](https://user-images.githubusercontent.com/26118508/103632806-d6e98080-4f7f-11eb-8016-70b50b80cbc2.png)

**Comment by WanManito** [comment]
![image](https://user-images.githubusercontent.com/26118508/103633006-1617d180-4f80-11eb-9ab4-b3010af4eac4.png)
![image](https://user-images.githubusercontent.com/26118508/103633208-5f682100-4f80-11eb-927c-171d37bcbeb1.png)
It can only find one

**Comment by jonasmalacofilho** [comment]
As I mentioned...

Your mileage will vary with HIDs: see libusb's ["Does libusb support USB HID devices?"](https://github.com/libusb/libusb/wiki/FAQ#does-libusb-support-usb-hid-devices) FAQ entry.  And your libusb debug output shows:

```
[ 0.255317] [000046a0] libusb: warning [hid_open] could not open HID device in R/W mode (keyboard or mouse?) - trying without
[ 0.256320] [000046a0] libusb: error [hid_open] could not open device \\.\USB#VID_03EB&PID_2421#123123123123#{A5DCBF10-6530-11D2-901F-00C04FB951ED} (interface 1): [2] 系统找不到指定的文件。
[ 0.256320] [000046a0] libusb: debug [libusb_open] open 1.19 returns -4
Traceback (most recent call last):
```

The fact that "cpthon hidapi" (it's cython-hidapi, right?) works as you expect does not change the sad truth that you simply may not be able to open some HID interfaces on Windows, with PyUSB or any other libusb wrapper.  You could try different drivers... but it's probably easier to stick to HIDAPI if you can.

---

> [...]
> It can only find one

Working as intended, there is only one USB device (USB device != USB interface).

Look, it seems that you want (or at least need) help.  If there was anything terribly wrong with your code, I would have told immediately... but there isn't.  There also doesn't appear to be anything wrong with PyUSB or libusb (apart from documented limitations).  It just doesn't seem to be a way to use libusb with that interface.[1]

If you don't mind, I suggest you open source your project, then ask for help in the right venues (like forums related to the specific domain you're working on, but also our [not so active] mailing list).

[1] Although I admit our communication has to been as clear as I normally like, so I might be missing something.

**Comment by WanManito** [comment]
@jonasmalacofilho Thank you for the interruption

**Comment by WanManito** [comment]
@jonasmalacofilho Thank you for your answer. Thank you
