### ISSUE TITLE
 `usb.core.find(find_all=True)` should raise an error if no backend is found

### ISSUE THREAD

**Issue by burnpanck** [pyusb/pyusb#353]
It seems that `usb.core.find(find_all=True)` simply does not return any devices when no backend is found. I would argue that this is misleading - we're asking pyusb to list us all available devices on the system, a request it cannot do if no backend is configured. Currently, all it does is log a few error messages, which however goes against the python zen "errors should not go unnoticed" - errors in the log are easily missed because they do not prevent the program from continuing. Given that pyusb aims at being pythonic, it should be explicit about errors such as missing backends.

**Comment by jonasmalacofilho** [comment]
Your argument is spot on... which is why PyUSB does already

https://github.com/pyusb/pyusb/blob/49e896b3de240ffa1b66779adf1d00d38cf6a108/usb/core.py#L1297

when no backend is available.
