### ISSUE TITLE
pyenv with M1 chip mac cannot find libusb?

### ISSUE THREAD

**Issue by ketaro-m** [pyusb/pyusb#361]
I'm using M1 mac and Big Sur 11.2.3, python version is 3.8.6 by pyenv.
I installed libusb at first, then created venv and pip-installed pyusb. But when I try using this module, the error like below occurred.

```
In [1]: import usb.core

In [2]: dev = usb.core.find()
---------------------------------------------------------------------------
NoBackendError                            Traceback (most recent call last)
<ipython-input-2-bbeca608b684> in <module>
----> 1 dev = usb.core.find()

~/pyusb/.venv/lib/python3.8/site-packages/usb/core.py in find(find_all, backend, custom_match, **args)
   1297                 break
   1298         else:
-> 1299             raise NoBackendError('No backend available')
   1300
   1301     if find_all:

NoBackendError: No backend available

In [3]:
```

However, if I changed python from pyenv python to homebrew-installed python, the problem above was solved. I guess it's due to the path dependency; homebrew python located in `opt/homebrew/opt/python@3.8` can find `/opt/homebrew/opt/libusb`, but pyenv python located in `~/.pyenv/shims/python` cannot. Is it right?

```
In [1]: import usb.core

In [2]: dev = usb.core.find()

In [3]:
```

This problem doesn't occur with Intel chip mac. Homebrew path is `/usr/local` in Intel processor, `/opt/homebrew` in ARM. 
Could you update this?

**Comment by jonasmalacofilho** [comment]
Basically, we use `ctypes.util.find_library` and that hasn't yet been patched for the 3.8 Python branch (see [Python issue 41100](https://bugs.python.org/issue41100)).  Homebrew's Python 3.8 apparently backports the fix in 3.9, which is why it works.

A bit more information can be found on a previous issue: #355.
