### ISSUE TITLE
USBError not defined in control.py

### ISSUE THREAD

**Issue by mpgerlek-apira** [pyusb/pyusb#372]
At control.py:178 (https://github.com/pyusb/pyusb/blob/d0272e4d030f1eced6b8ace2ee96c7432b3f5345/usb/control.py#L178), `USBError` is not defined. Presumably the reference should be to `core.USBError`.

**Comment by jonasmalacofilho** [comment]
Thanks!

**Comment by mpgerlek-apira** [comment]
Excellent response time, guys -- thanks so much!
