### ISSUE TITLE
Error Writing to USB Device

### ISSUE THREAD

**Issue by tcoupe** [pyusb/pyusb#403]
I am trying to write out to a KVM via USB to the keyboard port of the KVM. I want to switch between 2 inputs with keyboard emulation. The problem is the device identifies itself as an HID device and only shows a configuration with ENDPOINT_IN attribute. Writing to it gives an error. 

How can I set up a new configuration with ENDPOINT_OUT attribute and send characters to it?

Thanks for any help,
Terry

**Comment by jonasmalacofilho** [comment]
A host cannot create arbitrary configurations.  Only a change in the KVM firmware would make that possible.

That said, if a HID doesn't have an output endpoint, its control endpoint may be used for output reports (if necessary and as long as the specific protocol that the device uses expects/supports it).
