### ISSUE TITLE
Is there Pci usb card support

### ISSUE THREAD

**Issue by psxpetey** [pyusb/pyusb#407]
Will this work over pci ? Don’t see any info but if you have a pci usb card could Pyusb still work or will it need modification

**Comment by jonasmalacofilho** [comment]
_(I'm guessing you meant PCI-e)._

That's perfectly normal, most computers have one or more additional USB hubs on the PCI-e bus, even if they aren't in expansion cards (instead, directly soldered to the motherboard).

As long as the kernel sees the USB hub that the card provides, you should be set.
