### ISSUE TITLE
pyusb CDC example

### ISSUE THREAD

**Issue by sidprice** [pyusb/pyusb#408]
First, I am far from an expert with USB and libusb, so please forgive what may be a very newbie request.

I am working on a Python script to communicate with a CDC USB device, running on Windows 10. The device appears as a COM port in Device Manager, and it works with a different app (not written by me) using the default Windows driver. I have PyUSB installed, and the device is found using "usb.core.find". However, I have so far failed to get any further and I am looking for a simple read/write example as a reference.

I have done my trials with the default Windows driver and also, I have tried replacing the driver to libusb-win32 using Zadig.  I would hope I do not need to replace the default driver so that the device continues to work with other apps.

When I call (get_active_configuration" after the device is found, the exception is "Entity not Found."

**Comment by mcuee** [comment]
Please do not use pyusb with a CDC-ACM USB serial device. Please use pyserial instead.
