### ISSUE TITLE
usb.util.find_descriptor return NoneType

### ISSUE THREAD

**Issue by DataconTom** [pyusb/pyusb#429]
### Discussed in https://github.com/pyusb/pyusb/discussions/428

<div type='discussions-op-text'>

<sup>Originally posted by **DataconTom** June  8, 2022</sup>
![image](https://user-images.githubusercontent.com/69441947/172564197-902d813e-c864-4bc4-9d71-5efa829a092c.png)
![image](https://user-images.githubusercontent.com/69441947/172564363-b4b30a5b-80d6-4e1f-8c0f-27036a065415.png)
</div>

**Comment by jonasmalacofilho** [comment]
Please don't create a duplicate issue for a discussion unless it has already been concluded (in that discussion) that there's an actual bug or feature to be reported/requested.
