### ISSUE TITLE
optimization for get_string in usb/util.py

### ISSUE THREAD

**Issue by eszhaobing** [pyusb/pyusb#434]
We often come across some less canonical USB devices that don't have string descriptors. Therefore, it is recommended to return None directly instead of throwing an exception。

` if langid is None:
        langids = dev.langids
        if 0 == len(langids):
            raise ValueError("The device has no langid"
                             " (permission issue, no string descriptors supported or device error)")`

here it is a sample by` lsusb -v`

Bus 002 Device 003: ID 1a56:dd01  
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        32
  idVendor           0x1a56 
  idProduct          0xdd01 
  bcdDevice            2.00
  **iManufacturer           1 (error)
  iProduct                2 (error)**
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           41
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              200mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      36
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0007  1x 7 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0007  1x 7 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)

**Comment by jonasmalacofilho** [comment]
Not having string descriptors is _not_ what's going on with your device, or, at least, not what it's reporting there.  Both `iManufacturer` and `iProduct` are _non zero,_ indicating that they do exist.

Moreover, if you call `util.get_string()` with that `iSerial`, the optimization you suggested already exists: there will be no traffic to the device, and the function will immediately return `None`.  But we can't do that when something has clearly gone wrong (which could happen for a number of reasons)...
