### ISSUE TITLE
usb.core.find return wrong object

### ISSUE THREAD

**Issue by SharePlainCSource** [pyusb/pyusb#448]
libusb：1.0.26
pyusb：1.2.1
os:windows11
python:3.9.5
driver:libusbK 3.0.7.0

Plugin USB Device->Run Program->Unplug USB Device->Plugin USB Device
![image](https://user-images.githubusercontent.com/18573790/185543122-1b542851-0071-4480-b3d9-13e8ad5bdc8a.png)

**Comment by jonasmalacofilho** [comment]
Hi,

I'm failing to spot what's wrong in that screenshot.  Could you point me to the issue?

**Comment by SharePlainCSource** [comment]
> Hi,
> 
> I'm failing to spot what's wrong in that screenshot. Could you point me to the issue?

1.Plugin No.1 USB device to PC
2.Run Program
![image](https://user-images.githubusercontent.com/18573790/185823135-d27cd17f-74bd-4b79-a618-9425106b9b0a.png)
3.Plugin No.2 USB device,VID and PID the same as No.1 device
![image](https://user-images.githubusercontent.com/18573790/185825379-fcde51ab-1c89-4406-9546-ee47f4e388d9.png)

**Comment by jonasmalacofilho** [comment]
Again, what else did you expect the second screenshot to show?

Your code searches for a device with VID:PID 1a86:5512... and you find one.  So what exactly is wrong there?

**Comment by SharePlainCSource** [comment]
Sorry my mistake.
I thought the parameter find_all default vale is True.
