### ISSUE TITLE
The library need a stub-files to simplify usage

### ISSUE THREAD

**Issue by o-murphy** [pyusb/pyusb#513]
I can write a .pyi stubs for a library

**Comment by mcuee** [comment]
Maybe you want to elaborate what you want to achieve and give some examples. Thanks.

**Comment by o-murphy** [comment]
> Maybe you want to elaborate what you want to achieve and give some examples. Thanks.

already started with it #514 
I just want to adjust library to [PEP484](https://peps.python.org/pep-0484/) [PEP561](https://peps.python.org/pep-0561) specs

**Comment by jonasmalacofilho** [comment]
Duplicate of #470, keeping only the older issue.
