### ISSUE TITLE
Is it possible to emulate devices ?

### ISSUE THREAD

**Issue by asusdisciple** [pyusb/pyusb#523]
Hey I am pretty new to the usb club, I wonder if you guys could tell me if it is possible
with this library to emulate devices? For example I would like to connect my pc to a phone,
but the phone should recognize the pc as a microphone or headset, so that i can send audio data
through usb from my pc.

It would really be helpful if you can point me in the right direction since I havent done anything with usb communication yet.

best regards

**Comment by jonasmalacofilho** [comment]
That's not possible with this library.

Also, and AFAIK, your computer's USB controllers generally only operate in Host mode, which also wouldn't allow you to do what you want.  But you can start by taking a look at the docs for the [Linux USB Gadget API](https://www.kernel.org/doc/html/v4.17/driver-api/usb/gadget.html).
