### ISSUE TITLE
pip install pyusb fails on Ubuntu

### ISSUE THREAD

**Issue by salimfadhley** [pyusb/pyusb#55]
On ubuntu 14.4 / Python 3.4, latest version of pip

I expect this fault is an artefact of pyusb's deploy process. Fixing this bug would make pyusb easier for non-admin users to install.

---

pip install pyusb

Could not find a version that satisfies the requirement pyusb (from blink1->blink1buildlight==0.0.1) (from versions: 1.0.0a2, 1.0.0a2, 1.0.0a3, 1.0.0a3, 1.0.0b1)
  Some insecure and unverifiable files were ignored (use --allow-unverified pyusb to allow).
Cleaning up...
No distributions matching the version for pyusb (from blink1->blink1buildlight==0.0.1)
Storing debug log for failure in /home/sal/.pip/pip.log

**Comment by diegoherranz** [comment]
You can also use the `--pre` flag which will enable installing pre-releases and development releases. This way you don't have to deal with version numbers.

`pip install --pre pyusb`

**Comment by salimfadhley** [comment]
I think you can also use the version of pyusb supplied by Ubuntu. That's not neccecarily the latest version but it gets you out of the need to compile anything.
