### ISSUE TITLE
Implement libusbK backend

### ISSUE THREAD

**Issue by walac** [pyusb/pyusb#62]
[libusbK](http://libusbk.sourceforge.net) is a complete libusb library/driver for Windows systems. We should implement a backend for it.

**Comment by jonasmalacofilho** [comment]
No longer necessary:

> libusb Windows backend can support device using libusbK.sys (and libusb0.sys driver -- not recommended due to issues) through libusbk.dll provided by libusbK project. If libusbk.dll is present, it will use libusbK.dll as the intermediate library to support device using WinUSB driver. If libusbK.dll is not present, then it will directly talk to device using WinUSB using WinUSB API. libusb Windows also supports device using generic HID driver or usbdk driver.
—_[libusb/FAQ: libusb-win32, libusbK and libusb project](https://github.com/libusb/libusb/wiki/FAQ#libusb-win32-libusbk-and-libusb-project)_
